### ISSUE TITLE
Float Method 1 - Tie w/ rope

### ISSUE THREAD

**Issue by astorch98** [AguaClara/float_valve#10]
Attach 1" pipe to top of slider pipe by drilling two small holes on either side of slider pipe and tying rope through holes and around 1" pipe.
-Need rope that: 
     -will be strong enough to withstand being hit by tee (and other forces exerted on it)
     -will stay strong and in tact after being exposed to water

**Comment by FelixYuHengYang** [comment]
No rope because we think that the hose clamp idea would be more stable and longer lasting.
