### ISSUE TITLE
Float Method 3- Glue float to pipe

### ISSUE THREAD

**Issue by AlyciaStorch** [AguaClara/float_valve#12]
Cut a semicircle (or triangular shape)  on either side of the top of the slider pipe for the float to sit in. Use PVC glue to attach float to pipe.
-More stable than an entire hole through slider pipe
-If not a semicircular cut (bc it could be too difficult?) will there be enough contact area between slider pipe and float to keep float secure?
-will it be hard to make semicircular cuts perfectly straight across?

**Comment by FelixYuHengYang** [comment]
We cut a triangular since cutting a semicircle at the end of a pipe did not seem feasible.
