### ISSUE TITLE
Buoyant Force

### ISSUE THREAD

**Issue by AlyciaStorch** [AguaClara/float_valve#14]
Balance the mass of the float with buoyant force which is dependent on volume of PVC displacing water.

**Comment by FelixYuHengYang** [comment]
The weight of the slider pipe is .3192 kg without drilling any holes into it yet.

**Comment by FelixYuHengYang** [comment]
![float_calc](https://user-images.githubusercontent.com/31310824/37244558-dbbd91e6-2458-11e8-9d58-15ddeade07a9.PNG)
