### ISSUE TITLE
Float Ideas

### ISSUE THREAD

**Issue by AlyciaStorch** [AguaClara/float_valve#15]
-Use PVC Pipe as float
-cut circles the size of the pipe outer diameter out of pvc sheet and glue them to the ends of the pipe to seal it (instead of having to purchase caps)
-drill 2 holes in slider pipe and attach float with string through those holes
-potentially use multiple pipes for float, still tie central pipe to slider pipe and tie additional pipes to central pipe

**Comment by FelixYuHengYang** [comment]
We cut a triangle and plan to use about 7 inches of 1 inch pvc as float.

**Comment by FelixYuHengYang** [comment]
![float_calc](https://user-images.githubusercontent.com/31310824/37244628-c5c7129e-2459-11e8-8654-d05a753a3940.PNG)
