### ISSUE TITLE
Hose Clamp

### ISSUE THREAD

**Issue by AlyciaStorch** [AguaClara/float_valve#19]
We can use a hose clamp to attach float to slider pipe
-cut slits in pipe for hose clamp to go through 
-wrap hose clamp around foat
-tighten!

**Comment by ethan92429** [comment]
@astorch98 I'm wondering if you could drill a hole in the slider pipe that is the size of the OD of the float, and then use pipe fittings to make an E. About what size float would you need for an 8 inch float valve?

**Comment by FelixYuHengYang** [comment]
@ethan92429  sorry for the late response. We decided we wouldn't go with drilling a hole through the slider pipe and just cut a triangular incision into it. The float size for a 8 inch float valve would depend on how much it weighs. As I'm not sure if the density scales perfectly I can show you the calculations done for the small scale one.

**Comment by FelixYuHengYang** [comment]
![float_calc](https://user-images.githubusercontent.com/31310824/37244653-3fa03eba-245a-11e8-8abd-ededb3823740.PNG)

That is the mininum length. And the weight of the pipe was weighed after the triangular incision and before drilling all the holes(holes for flow, plugs to limit active length and hole for hose clamp).
