### ISSUE TITLE
Float Length/ Redesign

### ISSUE THREAD

**Issue by AlyciaStorch** [AguaClara/float_valve#28]
After calculating friction force between bushings and slider pipe, we determined the float would have to be 35.05 inches which is not feasible and too long for what we are using for testing. Thinking of having 3 pipes each with a length of about 12 inches connected by rectangles of pvc sheet on the ends which also act as end caps. The pipes will have some space between them so that the center one can still be hose clamped to the slider pipe.

**Comment by ethan92429** [comment]
Why not use PVC tees and elbows instead?

**Comment by AlyciaStorch** [comment]
We were expecting that these parts at the large scale sizes would cost more. Also, since there is not going to be water running through them, pressure is not a big concern.
