### ISSUE TITLE
Questions while testing 

### ISSUE THREAD

**Issue by FelixYuHengYang** [AguaClara/float_valve#30]
When does the slider pipe start to move? (In percentage and in distance0
How do we determine where the bottom of the float is? 
How can we standardize slider pipe length based on distribution tank height? 
- need to standaridze distances that we chose initially (arbitrary)
![img_20180320_202907](https://user-images.githubusercontent.com/31310824/37689787-91b67202-2c7d-11e8-8af5-12de9adae087.jpg)

**Comment by ethan92429** [comment]
You've got to experiment in the real world! I think the friction will be small. I think we'll learn the most about this the sooner we build it. Then we can start experimenting with different bushings, hole patterns, etc!

**Comment by AlyciaStorch** [comment]
Wrong ratio, instead of 3/100, should be 1/30. This gives us:
-h=72.93 cm
-(72.93 cm)/30= 2.43 cm
-the last 2.43 cm should fill in 2.1 min due to leaking

**Comment by AlyciaStorch** [comment]
Standardized water level on float: water level will be halfway up the height of the float pipes (h=radius of pipe). Given this, friction force between bushings and slider pipe, and density of water, you can solve for the required length of pipe. From there, depending on available space, # of float pipes can be determined. Function in design file
