### ISSUE TITLE
Exposure to atmospheric pressure

### ISSUE THREAD

**Issue by FelixYuHengYang** [AguaClara/float_valve#38]
@monroews 

When the valve shuts off water begins to back up and tries to exit through the hole that is used to expose it to atmospheric pressure. How do we tackle this problem? And will this be a problem in the field too?

**Comment by monroews** [comment]
I'm guessing this atmospheric pressure port is used to prevent applying the tap water pressure to your float valve. To mimic field conditions you would need to manually control the tap water valve to maintain a constant level in the atmospheric pressure port.

Best,
