### ISSUE TITLE
ORDER 2 INCH PIPE SUPPLIES

### ISSUE THREAD

**Issue by FelixYuHengYang** [AguaClara/float_valve#5]
2 inch pipe tee
2x 2in to 1.5 in bushings
1 X 1" pipe cap

**Comment by ethan92429** [comment]
Out of curiosity, are you guys planning to make an 8 inch float valve? That's huge! how are you going to supply enough water? Also, are you sure that my application down here needs the float valve to be 8 inches? I would have guessed 6 would've done the trick. Let me know when you have a python file I can look at, I'm curious to see how you are doing the headloss calculation.

**Comment by monroews** [comment]
This is the kind of decision that would have been good to run by me (or Ethan) before building. This is the expensive and difficult approach. In general it is better to start at a smaller scale and work up in scale as you develop proven methods.

**Comment by FelixYuHengYang** [comment]
Got it. Sorry I meant to respond earlier. We meant to do 4 inch and 3inch. Or 2 inch and 1.5 inch piping.

**Comment by FelixYuHengYang** [comment]
And @ethan we have a Python file on GitHub.
